name: ChatProtector
version: '1.1'
main: com.amazinaxel.chatprotector.ChatProtector
api-version: '1.20'
description: Cleans & protects the chat by preventing swearing, spamming, and more!
author: AmazinAxel
website: amazinaxel.com